### ISSUE TITLE
Dynamically add/remove an attribute

### ISSUE THREAD

**Issue by eugenk** [machty/emblem-site#33]
I'm struggling to dynamically add/remove the `disabled` attribute of a form button with emblem 0.9.0 and emberjs 2.12.1:

```emblem
button#the-id.a-class{action 'myAction'} disabled="{{v-get model 'isInvalid'}}" Submit
```
where the call of `v-get model 'isInvalid'` returns either `true` or `false`.

If this is rendered, the button is always disabled because the attribute `disabled` does have a value. Is there a way to fix this using emblem? I could not find an answer on the syntax page.

**Comment by thec0keman** [comment]
This looks like it may be more of an ember issue.  [Here](https://mammothhr.github.io/try-emblem/#/?result=%3Cbutton%20id%3D%22the-id%22%20%7B%7Baction%20'myAction'%7D%7D%20disabled%3D%22%7B%7Bv-get%20model%20'isInvalid'%7D%7D%22%20class%3D%22a-class%22%3ESubmit%3C%2Fbutton%3E) is the code in handlebar.

I think the issue here is you are assigning a string to an attribute, which in HTML will always evaluate to true.  Try using an expression:
```
button#the-id.a-class click={action 'myAction'} disabled={ v-get model 'isInvalid' } Submit
```

**Comment by eugenk** [comment]
This is working perfectly. Many thanks!

I didn't know I could assign an expression like this (without the quotation marks) to an attribute. Maybe I've skipped over it in the syntax page too fast.

**Comment by thec0keman** [comment]
It would help if the emblem documentation was up to date :)
